### ISSUE TITLE
question about conflict tokens

### ISSUE THREAD

**Issue by BitCalSaul** [longrongyang/STGC#1]
Hi thanks for your interesting work. I have two questions.
**Question 1:**
In section 3.3, your conflict elimination loss is said to encourage the reassignment of conflicting tokens to different experts. I am wondering if a conflicting token could still be routed to another expert where it conflicts with the average gradient direction.
**Question 2:**
Still in section 3.3, I'm not sure why there is a negative signal for the routing score. It seems related to the inverted routing score for the conflicting token. From my understanding, simply setting the routing score of the assigned expert for this conflicting token to the minimum should suffice to reduce the likelihood of that expert being selected for this token.

Thanks for your time and answers.

**Comment by longrongyang** [comment]
1. Response for Question 1: I understand your point. We have previously considered this issue but found it difficult to overcome this limitation. Since the token only passes the current expert and not other experts, the gradient can only show whether the token is in conflict with the holistic optimization direction of the current expert, and cannot clearly define the relationship with other experts. Therefore, we currently cannot find a good method to ensure that the token can be routed to the correct expert, but only to keep the token away from the expert that is currently in conflict.

2. Response for Question 2: The operation that you mention is equivalent to adding an MSE loss. Although the optimization direction is consistent with the current CE-based operation, the optimization speed of CE loss is superior to MSE loss (relevant research should be easy to find), and we have also conducted experiments, CE is better than MSE. A possible perspective: An analysis of the gradient of CE loss will reveal that when the probability of the sample on the ground-truth class is very small, CE will produce a very large gradient.

Thank you for your attention to our work. We are expanding our experiments on a larger scale public dataset provided by the Open-LLaVA-NeXT project, and after the experiments are completed, we will release our new results. (We spent some time in early July working on the public dataset ratio, so we are still in the experimental phase.)

**Comment by BitCalSaul** [comment]
Thanks for your quick response and detailed answers. 

**For Response 1:**
You're right, a token cannot determine which expert is best unless it has been forwarded to each expert for comparison.

**For Response 2:**
Thank you, I will look into relevant research to understand why CE loss is superior. I'm curious about the rationale behind taking a negative signal here. The only reason I can imagine is to assign a small gating value to the expert idmoe for the conflicting token (due to the negative signal), thus giving it a smaller chance compared to other experts. The CE Loss would then ensure this "new" chance remains smaller, effectively keeping the token away from the expert.

<img width="507" alt="image" src="https://github.com/user-attachments/assets/72b05441-1956-486c-b87a-53c6c271bf9f">

Additionally, after carefully reading this interesting work, I have Question 3:

**Question 3:**
I noticed that the load balancing loss is added to the total loss. I'm wondering if there is a natural conflict between load balancing and token conflict resolution. Since subtasks in the input vector space are naturally unevenly distributed, adding the load balancing loss might lead to more token conflicts within a single expert. What are your thoughts on this? Thanks.

**Comment by longrongyang** [comment]
Thank you again for your interest and attention.

1. Response for Question 2: Your understanding should be correct. Our motivation for taking a negative signal here is to minimize the routing score of the token on its current expert.

2. Response for Question 3: This is an interesting question. In our experiments, we found that our loss actually reduces the load balancing loss. This may be because the more tokens an expert has, the more likely it is to produce conflicting tokens. We will provide some statistical analysis and verification on this issue in the revised manuscript.
![1721527882824](https://github.com/user-attachments/assets/a43d06dd-4344-4d44-9a06-87fd64b87b77)
In the figure above, red represents the load balancing loss of the baseline, and blue represents the load balancing loss of our method.

**Comment by BitCalSaul** [comment]
Thanks for your detail response. Looking forward to the new results.
